### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by Manuestaire** [andyrichardson/atom-updater-linux#12]
### Issue Description
Updating from Atom Failed, got to download the file but could not install it

### Steps to reproduce
Running Update on Linux Mint

#### Actual result
Got the following error:
```
Something went wrong while attempting to update atom
Hide Stack Trace
Error: Command failed: SHELL=/bin/bash pkexec rpm -U /tmp/atom-updater-linux.installer
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
error: Dependencias fallidas:
	lsb-core-noarch se necesita por atom-1.28.1-0.1.x86_64
	libXss.so.1()(64bit) se necesita por atom-1.28.1-0.1.x86_64
	libsecret-1.so.0()(64bit) se necesita por `atom-1.28.1-0.1.x86_64
```

### Additional info

**Atom version:** 1.27.2 x64

**Package version:** 1.2.2

**Operating System:** Mint 17.2

**Comment by andyrichardson** [comment]
Hi @Manuestaire thanks for the report.

You're using a Debian based OS and for some unusal reason it looks as though you have _rpm_ installed.

If you navigate to the package settings, you can manually specify that you want to install the Debian package version.

I'm going to close the issue but feel free to reopen if your problem persists.

**Comment by Manuestaire** [comment]
Thank you, that solved the issue

(btw I hope this response doesn't reopen the issue :S)

**Comment by andyrichardson** [comment]
To prevent others encountering this issue, I've made some changes to the way in which the OS (and therefore primary package manager) is detected - #20.
