### ISSUE TITLE
Updater is not working

### ISSUE THREAD

**Issue by zonar-jaybose** [andyrichardson/atom-updater-linux#13]
### Issue Description
I'm in a running instance of Atom.
The process begins, and asks if I want to install the latest Atom.
I click on the button to proceed. 
The process downloads the needed archive, and then asks for my password to proceed.
Then asks if for a restart of Atom.
I perform the restart, and then the process asks if I want to install the latest Atom, again.
I've performed this step at least 6 times. There is no change.

### Steps to reproduce
1. Start Atom.
2. The process begins, and asks if I want to install the latest Atom.
3. I click on the button to proceed. 
4. After the process downloads the needed archive, it will ask for you password to proceed.
5. You will be asked if it is fine to restart Atom.
6. Accept the restart.

#### Expected result
The latest version of Atom to be installed. In my case, that would be 1.29.0

#### Actual result
My Atom is still 1.28.2

### Additional info

**Atom version:** 1.28.2

**Package version:** 1.2.2

**Operating System:** Ubuntu 18

**Comment by andyrichardson** [comment]
Hey, thanks for the report. 

I haven't been able to reproduce this issue. My first piece of advice would be to manually specify the package type in the package settings as `deb`.

**Comment by GergelyLakatos** [comment]
I have a similar problem on opensuse 15.0. 
My atom version 1.29.0 
I click to update, the downloading is success, but the install is not able to finish without error.

The error:

> Error: Command failed: SHELL=/bin/bash pkexec dpkg -i /tmp/atom-updater-linux.installer
> Cannot run program dpkg: No such file or directory

**Comment by andyrichardson** [comment]
@GergelyLakatos this [package is now deprecated](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux) - if you still need to use it, please manually specify the package type as `rpm` in the Atom package settings.
