### ISSUE TITLE
Installing updates failes on Ubuntu 16.04

### ISSUE THREAD

**Issue by derMart** [andyrichardson/atom-updater-linux#15]
### Issue Description
The updater notifies of a new update.
After downloading it asks to install.
After the sudo password promt I get this error:
```
Error: Command failed: SHELL=/bin/bash pkexec rpm -U /tmp/atom-updater-linux.installer
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
error: Failed dependencies:
	lsb-core-noarch is needed by atom-1.29.0-0.1.x86_64
	libXss.so.1()(64bit) is needed by atom-1.29.0-0.1.x86_64
	libsecret-1.so.0()(64bit) is needed by atom-1.29.0-0.1.x86_64
```

**Atom version:**
1.27.1
**Package version:** 
1.2.2
**Operating System:**
Ubuntu 16.04

**Comment by andyrichardson** [comment]
This is a duplicate of #12

**Comment by derMart** [comment]
Thank you very much for the response. However, I am surprised that you closed this ticket. I am also suprised that the duplicate is closed. Apparently the issue is not fixed. In #12 you propose a workaround, but that does not solve the issue that the plugin for "some unusal reason" looks as though rpm is installed, although it is not, because a debian based system is used. Please repoen this ticket or #12 until the problem is solved. If you need some more information to do that I am happy to help.

Thank you very much.

**Comment by andyrichardson** [comment]
In your case, rpm is installed - try running `whereis rpm`.

That being said, given multiple people are encountering this issue, see the amendments in #20.
