### ISSUE TITLE
Continuous updating

### ISSUE THREAD

**Issue by fvhockney** [andyrichardson/atom-updater-linux#7]
Package continuously tries to install the newest version even after a successful update.

#### Operating System
* Ubuntu 16.04

#### Settings:
* check on startup
* auto-detect

**Comment by andyrichardson** [comment]
Hey, @fvhockney, thanks for submitting this issue.

I've created a new template for submitting issues in order to assist in better understanding the problem. Can you fill it out.

```
### Issue Description
[Description here]

### Steps to reproduce
 1. [Step one here]
 2. [Step two ...]

#### Expected result
[What you expected to happen]

#### Actual result
[What actually happened]

### Additional info

**Atom version:** [e.g. v1.0.0]

**Package version:** [e.g. v0.2.0]

**Operating System:** [e.g. Fedora]

```

**Comment by andyrichardson** [comment]
I'm closing this as the complexity of installation has been hugely reduced as of _v1.2.2_.
